name: CI

on: [ push ]

env:
  CI: true
  RAILS_ENV: test

jobs:

  lint:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      -
        name: Install ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      -
        name: "Lint / rubocop"
        run: |
          gem install rubocop
          gem install rubocop-performance
          gem install rubocop-rake
          gem install rubocop-rspec
          gem install rubocop-gitlab-security
          gem install rubocop-rails
          gem install rubocop-capybara
          gem install rubocop-factory_bot
          rubocop --parallel
      -
        name: Install dependencies
        run: bin/bundle install --jobs 4 --retry 3
      -
        name: "Lint / erblint"
        run: bin/erblint --lint-all
      -
        name: "Security / brakeman"
        run: |
          gem install brakeman
          brakeman --exit-on-warn --no-progress --color --output /dev/stdout
      -
        name: "Security / bundle-audit"
        run: |
          gem install bundle-audit
          bundle-audit check --update -v
      -
        name: "Test / unit tests"
        run: bin/bundle exec rspec spec --exclude-pattern "spec/system/**/*_spec.rb"

      - name: "Prepare system tests"
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:drop db:create db:schema:load
          bin/rails db:migrate
          bin/rails assets:precompile
      -
        name: "Test / system tests"
        run: bin/bundle exec rspec spec/system
